CREATE SEQUENCE GESTAO.SEQ_PESSOA START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.PESSOA
(
    ID_PESSOA NUMBER PRIMARY KEY,
    NOME      VARCHAR2(50) NOT NULL,
    REGISTRO  VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE GESTAO.SEQ_MODELO START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.MODELO
(
    ID_MODELO  NUMBER PRIMARY KEY,
    NOME       VARCHAR2(50) NOT NULL,
    FABRICANTE VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE GESTAO.SEQ_VEICULO START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.VEICULO
(
    ID_VEICULO              NUMBER PRIMARY KEY,
    ANO                     NUMBER NOT NULL,
    KM                      NUMBER NOT NULL DEFAULT 0,
    PLACA                   VARCHAR2(10) NOT NULL,
    STATUS                  VARCHAR2(1) NOT NULL CHECK (STATUS IN ('S', 'N')),
    MODELO_ID               NUMBER NOT NULL,
    TIPO_COMBUSTIVEL        VARCHAR2(20) NOT NULL CHECK (TIPO_COMBUSTIVEL IN ('GASOLINA_ETANOL', 'GASOLINA', 'DIESEL', 'ELETRICO', 'HIBRIDO' 'ETANOL','GNV')),
    DATA_DE_CADASTRO        DATE   NOT NULL,
    DATA_ULTIMA_ATUALIZACAO DATE   NOT NULL,
    CONSTRAINT FK_VEICULO_MODELO_ID FOREIGN KEY (MODELO_ID) REFERENCES GESTAO.MODELO (ID_MODELO)
);

CREATE SEQUENCE GESTAO.SEQ_BAIXA_VEICULO START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.BAIXA_VEICULO
(
    ID_BAIXA_VEICULO NUMBER PRIMARY KEY,
    VEICULO_ID       NUMBER    NOT NULL,
    DATA_HORA        TIMESTAMP NOT NULL,
    KM_BAIXA         NUMBER    NOT NULL,
    DESCRICAO        VARCHAR2(255) NOT NULL,
    CONSTRAINT FK_BAIXA_VEICULO_VEICULO_ID FOREIGN KEY (VEICULO_ID) REFERENCES GESTAO.VEICULO(ID_VEICULO)
);

CREATE SEQUENCE GESTAO.SEQ_HISTORICO_VEICULO START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.HISTORICO_VEICULO
(
    ID_HISTORICO_VEICULO NUMBER PRIMARY KEY,
    DATA_HORA_SAIDA      TIMESTAMP NOT NULL,
    KM_SAIDA             NUMBER    NOT NULL,
    DATA_HORA_RETORNO    TIMESTAMP,
    KM_RETORNO           NUMBER,
    DESCRICAO            VARCHAR2(100),
    VEICULO_ID           NUMBER    NOT NULL,
    BAIXA_VEICULO_ID     NUMBER,
    PESSOA_ID            NUMBER NOT NULL,
    CONSTRAINT FK_HISTORICO_VEICULO_VEICULO_ID FOREIGN KEY (VEICULO_ID) REFERENCES GESTAO.VEICULO (ID_VEICULO),
    CONSTRAINT FK_HISTORICO_VEICULO_BAIXA_VEICULO_ID FOREIGN KEY (BAIXA_VEICULO_ID) REFERENCES GESTAO.BAIXA_VEICULO (ID_BAIXA_VEICULO),
    CONSTRAINT FK_HISTORICO_VEICULO_PESSOA_ID FOREIGN KEY (PESSOA_ID) REFERENCES GESTAO.PESSOA (ID_PESSOA)
)



